spring:
  application:
    name: myapp
  port: 8080
    # For development environment
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: ["*", "prometheus" ]





