# Test profile configuration
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    # Optionally configure connection pooling (HikariCP is default in Spring Boot)
    hikari:
      maximum-pool-size: 10  # Maximum number of connections in the pool
      minimum-idle: 5        # Minimum number of idle connections
      pool-name: HikariCP     # Optional name for your connection pool
  sql:
    init:
      #schema-location: classpath:/sql/schema.sql
      #data-location: classpath:sql/data.sql
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # Make sure to use MySQLDialect    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  logging:
    level:
      root: ERROR
      org.springframework: ERROR